#!/usr/bin/env bash
# Regenerates the badge block in README.md between the markers:
#   <!-- BADGES:START -->
#   <!-- BADGES:END -->
#
# Usage: ./scripts/gen-badges.sh [path/to/README.md]
#
# Edit the data inside generate() — one line per badge:
#   badge "<DisplayName>" "<HexColor>" "<URL>" [slug] [alt]
# slug defaults to display name with spaces -> underscores.
# alt  defaults to display name.

set -euo pipefail

README="${1:-README.md}"
START_MARK='<!-- BADGES:START -->'
END_MARK='<!-- BADGES:END -->'

badge() {
    local name="$1" color="$2" url="$3"
    local slug="${4:-}" alt="${5:-}"
    [[ -z "$slug" ]] && slug="${name// /_}"
    [[ -z "$alt"  ]] && alt="$name"
    printf '<a href="%s"><img style="height: 36px" src="https://img.shields.io/badge/%s-%%23%s.svg?style=for-the-badge&logoColor=white" alt="%s" class="logo"></a>\n' \
        "$url" "$slug" "$color" "$alt"
}

section() {
    printf '\n<h4>%s</h4>\n' "$1"
}

generate() {
    printf '<!-- Auto-generated by scripts/gen-badges.sh — edit data there, then run the script. -->\n'

    section ""
    badge "C"      "283593" "https://en.wikipedia.org/wiki/C_(programming_language)"
    badge "C++"    "00599C" "http://www.cplusplus.org/" "C%2B%2B"
    badge "Python" "3776AB" "https://www.python.org/"
    badge "Java"   "E76F00" "https://www.java.com/en/"
    badge "Rust"   "B7410E" "https://www.rust-lang.org/"
    badge "Bash"   "4EAA25" "https://en.wikipedia.org/wiki/Bash_(Unix_shell)"
    badge "MATLAB" "0076A8" "https://www.mathworks.com/products/matlab.html"

    # section "Operating Systems"
    badge "Linux"   "2D3E50" "https://www.kernel.org/"
    badge "RHEL"    "EE0000" "https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux"
    badge "Windows" "0078D6" "https://www.microsoft.com/el-gr/windows"

    # section "Virtualization &amp; Hypervisors"
    badge "KVM"        "A80030" "https://www.linux-kvm.org/"
    badge "Proxmox"    "E57000" "https://www.proxmox.com/"
    badge "VMware"     "607078" "https://www.vmware.com/"
    badge "VirtualBox" "183A61" "https://www.virtualbox.org/"

    # section "Containers &amp; Orchestration"
    badge "Docker"     "2496ED" "https://www.docker.com/"
    badge "Kubernetes" "326CE5" "https://kubernetes.io/"
    badge "k3s"        "E89211" "https://k3s.io/"
    badge "k9s"        "00A8E0" "https://k9scli.io/"

    # section "Infrastructure Automation"
    badge "Ansible" "1A1918" "https://www.ansible.com/"

    # section "Servers &amp; Networking"
    badge "HP ProLiant" "0096D6" "https://www.hpe.com/us/en/servers/proliant.html"
    badge "MikroTik"    "293239" "https://mikrotik.com/"
    badge "Nginx"       "009639" "https://www.nginx.com/"

    # section "Databases"
    badge "PostgreSQL" "336791" "https://www.postgresql.org/"
    badge "MySQL"      "4479A1" "https://www.mysql.com/"
    badge "SQLite"     "003B57" "https://www.sqlite.org/"

    # section "Microcontrollers &amp; Hardware Platforms"
    badge "ARM"     "0091BD" "https://www.arm.com/"
    badge "STM32"   "4DA3DD" "https://www.st.com/en/microcontrollers-microprocessors/stm32-32-bit-arm-cortex-mcus.html"
    badge "AVR"     "BF1E2D" "https://en.wikipedia.org/wiki/AVR_microcontrollers"
    badge "ESP8266" "E7352C" "https://www.esp8266.com/"

    # section "Embedded Frameworks &amp; Libraries"
    badge "PlatformIO" "F5822A" "https://platformio.org/"
    badge "TinyOS"     "4D4D4D" "http://www.tinyos.net/"
    badge "TinyUSB"    "6C757D" "https://www.tinyusb.org/"

    # section "Build &amp; Debug Tools"
    badge "GNU Make" "A42E2B" "https://www.gnu.org/software/make/manual/make.html"
    badge "CMake"    "064F8C" "https://cmake.org/"
    badge "GDB"      "A42E2B" "https://www.sourceware.org/gdb/"
    badge "Valgrind" "7B1FA2" "https://valgrind.org/"

    # section "Version Control"
    badge "Git"    "F05032" "https://git-scm.com/"
    badge "GitHub" "181717" "https://github.com/"

    # section "Editors &amp; Terminal"
    badge "Vim"  "019733" "https://www.vim.org/"
    badge "tmux" "128410" "https://github.com/tmux/tmux/wiki"

    # section "IDEs"
    badge "VS Code"        "007ACC" "https://code.visualstudio.com/"
    badge "Visual Studio"  "5C2D91" "https://visualstudio.microsoft.com/"
    badge "JetBrains"      "000000" "https://www.jetbrains.com/"
    badge "Eclipse"        "2C2255" "https://www.eclipse.org/"
    badge "STM32CubeIDE"   "03234B" "https://www.st.com/en/development-tools/stm32cubeide.html"
    badge "Android Studio" "073042" "https://developer.android.com/studio"
    badge "Arduino"        "00979D" "https://www.arduino.cc/"

    # section "EDA / PCB Design"
    badge "KiCad"     "314CB0" "https://www.kicad.org/"
    badge "Eagle CAD" "A86F2C" "https://www.autodesk.com/products/eagle/overview"
    badge "Fritzing"  "C99A00" "https://fritzing.org/"

    # section "Robotics &amp; Computer Vision"
    badge "ROS"    "22314E" "https://www.ros.org/"
    badge "OpenCV" "5C3EE8" "https://opencv.org/"

    # section "Parallel Computing &amp; Interop"
    badge "PThreads" "3D6117" "https://en.wikipedia.org/wiki/Pthreads"
    badge "OpenMP"   "00599C" "https://www.openmp.org/"
    badge "pybind11" "306998" "https://pybind11.readthedocs.io/en/stable/basics.html"

    # section "Static Site &amp; Typesetting"
    badge "Hugo"  "FF4088" "https://gohugo.io/"
    badge "LaTeX" "008080" "https://www.latex-project.org/"
    badge "Typst" "239DAD" "https://typst.app/"

    # section "AI / LLM Tools"
    badge "Claude"  "D97757" "https://www.anthropic.com/claude"
    badge "Codex"   "412991" "https://github.com/openai/codex"
    badge "Gemini"  "8E75B2" "https://gemini.google.com/"
    badge "Ollama"  "000000" "https://ollama.com/"

    # section "Hardware Protocols"
    badge "USB"  "2D2D2D" "https://en.wikipedia.org/wiki/USB"
    badge "I²C"  "3F51B5" "https://en.wikipedia.org/wiki/I%C2%B2C" "I%C2%B2C" "I2C"
    badge "SPI"  "009688" "https://en.wikipedia.org/wiki/Serial_Peripheral_Interface"
    badge "UART" "FF5722" "https://el.wikipedia.org/wiki/UART"
}

if [[ ! -f "$README" ]]; then
    echo "error: $README not found" >&2
    exit 1
fi
if ! grep -q "$START_MARK" "$README" || ! grep -q "$END_MARK" "$README"; then
    echo "error: markers $START_MARK / $END_MARK missing in $README" >&2
    exit 1
fi

block="$(generate)"

awk -v start="$START_MARK" -v end="$END_MARK" -v block="$block" '
    $0 ~ start { print; print block; skip=1; next }
    $0 ~ end   { skip=0 }
    !skip      { print }
' "$README" > "$README.tmp" && mv "$README.tmp" "$README"

echo "regenerated badge block in $README"
